use std::error::Error;

pub fn run() -> Result<(), Box<dyn Error>> {
    println!("Day 2");
    Ok(())
}
